version: '3'

networks:
  local:

services:
  master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    hostname: master
    working_dir: /usr/spark
    environment:
      INIT_DAEMON_STEP: setup_spark
      SPARK_CONF_DIR: /conf
      MASTER: spark://master:7077
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
      - 9200
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - $PWD/conf/master:/conf
      - $PWD/data:/tmp/data
      - $PWD/app/build:/build
    networks:
      local:

  worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    hostname: worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1500mb
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_MASTER: spark://master:7077
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 7077
      - 8881
      - 9200
    ports:
      - 8082:8082
    volumes:
      - $PWD/conf/worker:/conf
      - $PWD/data:/tmp/data
    networks:
      local:
    depends_on:
      - master
